name: Deploy to EC2 via Load Balancer

on:
  push:
    branches:
      - main  # Cambia por tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p $HOME/.ssh  # Crea el directorio .ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > $HOME/.ssh/id_rsa  # Guarda la clave privada SSH
        chmod 600 $HOME/.ssh/id_rsa  # Cambia los permisos de la clave
        ssh-keyscan -H HelloWorldALB-755227875.us-east-1.elb.amazonaws.com >> $HOME/.ssh/known_hosts  # Agrega el ELB a los hosts conocidos

    - name: Deploy to EC2 instances behind ELB
      run: |
        ssh -i $HOME/.ssh/id_rsa ec2-user@HelloWorldALB-755227875.us-east-1.elb.amazonaws.com << 'EOF'
          cd HelloWorldPY  # Cambia a la carpeta de tu aplicación en la EC2
          git pull  # Trae los últimos cambios
          pkill -f python  # Detiene cualquier instancia previa de la aplicación
          nohup python3 app.py > app.log 2>&1 &  # Ejecuta la aplicación en segundo plano
        EOF