name: Deploy to EC2 (via Load Balancer)

on:
  push:
    branches:
      - main  # Cambia si tu rama principal tiene otro nombre

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H HelloWorldALB-755227875.us-east-1.elb.amazonaws.com >> ~/.ssh/known_hosts  # Usamos el DNS del ELB

    - name: Deploy to EC2 instances behind ELB
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@HelloWorldALB-755227875.us-east-1.elb.amazonaws.com << 'EOF'
          cd HelloWorldPY
          git pull  # Esto descarga los últimos cambios
          pkill -f python  # Detiene cualquier instancia previa de la aplicación
          nohup python3 app.py > app.log 2>&1 &  # Vuelve a ejecutar la aplicación en segundo plano
        EOF