name: Deploy to EC2

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar SSH para conectar a EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HelloWorldSecret }}

      # 3. Configurar Python y dependencias
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 4. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Desplegar a EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.HelloWorldSecretPub }} << 'EOF'
            cd /home/ec2-user/HelloWorldPY
            git pull origin main
            sudo systemctl restart flaskapp  # Asumiendo que tu servicio se llama flaskapp
          EOF
